apiVersion: v1
kind: Namespace
metadata:
  name: demo1
  labels:
    name: demo1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo1
  namespace: demo1
  labels:
    app: nginx
    env: dev3
spec:
  containers:
  - name: nginx
 #   image: nginx:1.14.2
    image: ssdeepu/demo:blue
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    ports:
    - containerPort: 8080
---
    apiVersion: v1
    kind: Service
    metadata:
      name: demo1-service
      namespace: demo1
    spec:
      selector:
        app: nginx
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
      type: LoadBalancer