apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo1
  namespace: demo1
  labels:
    app: nginx
    env: devtest1
spec:
  containers:
  - name: nginx
 #   image: nginx:1.14.2
    image: ssdeepu/demo:green
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    ports:
    - containerPort: 8080

