apiVersion: v1
kind: Namespace
metadata:
  name: demo1
  labels:
    name: demo1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo1
  namespace: demo1
spec:
  containers:
  - name: nginx
 #   image: nginx:1.14.2
    image: nginx:latest
    ports:
    - containerPort: 80
