    apiVersion: v1
    kind: Service
    metadata:
      name: demo1-service
      namespace: demo1
    spec:
      selector:
        app: nginx
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
      type: LoadBalancer