---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: falco-helmrepo
  namespace: flux-system
spec:
  interval: 5m0s
  type: oci
  url: oci://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco-helmrelease
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  releaseName: falco-scanner
  chart:
    spec:
      chart: nginx-ingress
      version: 4.21.3
      sourceRef:
        kind: HelmRepository
        name: falco-helmrepo
      interval: 5m
  targetNamespace: falco