---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: falco-helmrepo
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://ghcr.io/falcosecurity/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  releaseName: falco
  chart:
    spec:
      chart: falco
      version: 4.21.3
      sourceRef:
        kind: HelmRepository
        name: falco-helmrepo
      interval: 5m
  targetNamespace: falco