---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-helmrepo
  namespace: flux-system
spec:
  interval: 5m0s
  type: oci
  url: oci://registry-1.docker.io/nginxcharts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-helmrelease
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: nginx-helmrepo
      interval: 5m
  targetNamespace: nginx-ingress
  values:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        httpPort:
          enable: false
      replicaCount: 3
      disableIPV6: true